version: '3.5'

services: 
  bungeecord:
    container_name: minecraft_bungeecord
    image: openjdk:jdk-buster
    ports: 
      - "25565:25565"
    expose: 
      - "25565"
    volumes: 
      - "./mine_server/BungeeCord:/usr/src"
    working_dir: /usr/src
    command: bash -c "java -Xmx512m -Xms512M -jar *.jar nogui"
    
  lobby:
    container_name: minecraft_lobby
    image: openjdk:jdk-buster
    ports: 
      - "25570:25570"
    expose: 
      - "25570"
    volumes: 
      - "./mine_server/lobby:/usr/src"
    working_dir: /usr/src
    command: bash -c "java -Xmx1024m -Xms1024M -jar *.jar nogui"

  
  survival:
    container_name: minecraft_survival
    image: openjdk:jdk-buster
    ports: 
      - "25571:25571"
    expose: 
      - "25571"
    volumes: 
      - "./mine_server/survival:/usr/src"
    working_dir: /usr/src
    command: bash -c "java -Xmx1024m -Xms1024M -jar *.jar nogui"

